### ISSUE TITLE
bug: alpha2 water interaction with flower is wrong

### ISSUE THREAD

**Issue by MilkissWhite** [13rac1/Minecraft-Water-Erosion#11]
minecraft 1.15.2
forge 31.1.12
watererosion 1.15.2-forge-1.1.0-alpha2

water that flowing above flower happen something wrong. it break flower but immediatly re-plant. and repeat it rapidly.

it can reproduce easilly.

here is screenshot.
1 - before water flow.

![watererosion_bug001](https://user-images.githubusercontent.com/60180416/74867454-0909e800-5398-11ea-8cd2-e29f58574ca4.png)

2 - while water flowing. this situation make noise(flower breaking sound). and you can see dropped flower item. it's not new one. broken flower block don't disappear.

![watererosion_bug002](https://user-images.githubusercontent.com/60180416/74867469-11622300-5398-11ea-93b2-7fe023e98b0a.png)

thx for reading

**Comment by 13rac1** [comment]
Weird. Thanks for screenshots! Flowers are not _supposed_ to be  "erodable" or "decayable". Maybe a boolean is flipped. I'll attempt to reproduce and add details.

**Comment by 13rac1** [comment]
What other mods are you running? I cannot reproduce in development. Can you reproduce the issue on your machine without the other mods? I see at least a minimap mod.

![2020-02-19_11 49 07](https://user-images.githubusercontent.com/195061/74870087-fa76ee80-530d-11ea-96e7-b8260aaa8483.png)
![2020-02-19_11 49 20](https://user-images.githubusercontent.com/195061/74870096-fe0a7580-530d-11ea-9825-739fd6f3792d.png)

**Comment by MilkissWhite** [comment]
I also couldn't reproduce if I remove all my mod except mixinbootstrap and water-erosion.
I'll test some supecious mods.

**Comment by MilkissWhite** [comment]
I did reproduce. VanillaTweaks (https://github.com/StrikerRockers-Mods/VanillaTweaks) mod making this problem. water-erosion have no relation with this wierd bug. I'll go to bug report that github.
sorry about I made you confuse.
