### ISSUE TITLE
Make it ignore farmland please

### ISSUE THREAD

**Issue by TybaIt** [13rac1/Minecraft-Water-Erosion#12]
We are building machines with water flowing down so it farms all the plants and you can just collect them.
But the farmland is eroding.
Please, make it ignore dirt blocks which a player used a hoe on.

We cannot use the mod otherwise

**Comment by 13rac1** [comment]
Erosion actually destroys farmland in real life. Can you think of a way to keep this realistic while not breaking the machines?

The quick answer of course is #1 

Possible long term better solution: How long are you flowing water to collect the plants? Aren't you flowing some water and then shutting it off? What if water had exist at a specific block position for a minimum period of time before it would erode? I could create a "Minimum existence time before erosion" check by adding a timestamp of last block change. :thinking:

**Comment by TybaIt** [comment]
The machines lets water flow down and collects crops along  the way. It even erodes farmland along the way directly below. 

> Erosion actually destroys farmland in real life. Can you think of a way to keep this realistic while not breaking the machines?

The thing here is that too much realism is annoying, especially for a case like this. If I wanted extreme "realism" why do we play games? My point is that it should enhance the game experience not introduce new hassles the core game already has enough off. (Water crops, hunger, mobs, leveling, wooden structures during thunderstorms, getting resources for structures)

> The quick answer of course is #1 - Feature: Configurable Erosion Odds and Types

please implement this so we can actually use this wonderful mod to enhance the nature and environment we are playing in without it interupting our gameplay.

**Comment by 13rac1** [comment]
>  If I wanted extreme "realism" why do we play games?

I play games for the realism, to experience a reality not currently available. Yes, though, many people play for escape.

> The goal with immersiveness should be to "approach" realism while still keeping it a game.

That is already exactly my goal; why my suggested long term solution would resolve your issue actually more realistically than the current functionality. Adding yet-another minor "hassle" is my intention. I don't want an easier game. I want more realism, but within Minecraft's low resolution reality. :laughing: I'm happy to implement the an optional realism reduction for you, but must stay true to my goal.

I'm considering this as another vote for the next feature being configuration files. I'll implement after I complete 1.1.0

**Comment by 13rac1** [comment]
Created V1.2.0 milestone. Added this issue and #1

**Comment by TybaIt** [comment]
You can stay true to your goal. 
I would definitely add options to disable these "difficult increasing" stuff you want to add for your own pleasure. While you enjoy having to replace your farmblocks or repair your machines, others might not, but they love the eroding.  You benefit from more users using your mod if anyone can adjust it to their enjoyment, they give you ideas and you get happy for others using it. winwin

**Comment by 13rac1** [comment]
> You can stay true to your goal.

Thanks for allowing it :laughing: 

>  While you enjoy having to replace your farmblocks or repair your machines

No, I don't. Making erosion more realistic as in #13 will solve this problem correctly.

> There is probably a propery tag that dirt blocks use for that.

They are separate blocks as of 1.13+ where primary development occurs. I need to determine a maintainable way to support pre-1.13 block types.

**Comment by TybaIt** [comment]
Oh well. We are playing on 1.15.2 I don't know who still plays on 1.12.2 except those playing with _Conquest Reforged_  . ^^
