### ISSUE TITLE
Is Water Erosion broken for 1.15.2?

### ISSUE THREAD

**Issue by Lokuzt** [13rac1/Minecraft-Water-Erosion#21]
I'm using Water Erosion 1.1.2 with forge version 31.2.24 for minecraft 1.15.2. I've cranked the random ticks up to even 6000 and nothing seems to be happening, although it seems to work perfectly in the 1.16.1 version. So, out of lack of knowledge on the history of this mod; Is the mod broken and never going to be fixed for 1.15.2? Or is it just me, in which case, what could I do to fix it?

**Comment by Lokuzt** [comment]
Oh my god... I'm so sorry. I totally blinded and didn't notice the required dependency for this version. After adding the MixinBootstrap it works fine now. Do I close this issue? or delete it? Sorry, total newb in github.

**Comment by 13rac1** [comment]
Glad to see you got it worked out. Thanks for following up, no problem. :grin:
