### ISSUE TITLE
Idea: Lava Erosion?

### ISSUE THREAD

**Issue by Lokuzt** [13rac1/Minecraft-Water-Erosion#22]
To make it up for the mess I made before, I decided to share something that came to my mind after trying out this mod; Lava erosion. I don't know much about geography(?) so maybe this doesn't really happen, but a quick google gave me this result: [Mars Education | Lava Flows](https://marsed.asu.edu/mep/583#:~:text=Erosion%20by%20lava%20operates%20much,bonded%20pieces%20of%20earlier%20flows.) so maybe it does happen. I just thought it could work similarly to water, but maybe affect blocks' degradation differently?
Either way, loving this mod. Cheers!

**Comment by 13rac1** [comment]
:thinking: It would function similarly. The first issue which comes to mind is that I don't want to dig holes in stone, since it could dig downwards forever (aka to the bedrock.) What rules could we put in place to avoid "holes through the world"?

**Comment by Lokuzt** [comment]
The minecraft's world would have an actual core! /jk
Maybe I don't fully understand the mod, but what about making the lava degrade Stone into Gravel or some other block which may not react to lava's erosion? that could be a way, although it would make lava's erosion not do much, really. 
Another approach would be to make it only work under a certain height layer, behaving like how it is hotter the deeper you go, maybe Y = 20 or 16 would be when this happens? Then the effect of the "holes through the world" wouldn't make that big of an impact. o:

**Comment by 13rac1** [comment]
Don't worry about not understanding how the Water Erosion works. I'm interested in how you think Lava _could_ work. I cannot promise I'll work on ASAP or anything, but I'm curious.

> what about making the lava degrade Stone into Gravel or some other block which may not react to lava's erosion?

IRL lava wouldn't _erode_ in the same sense as water erodes these blocks. This has a good explanation: [Why doesn’t lava melt the side of the volcano?](https://theconversation.com/curious-kids-why-doesnt-lava-melt-the-side-of-the-volcano-90683) Lava doesn't melt rocks or dirt (does dirt even melt? I doubt it...) Found an existing Lava mod: [Lava Dynamics](https://www.curseforge.com/minecraft/mc-mods/lava-dynamics). It doesn't work exactly as you describe though.

**Comment by Lokuzt** [comment]
Yeah, I think I confused/merged erosion and melting on my thought process. Oops
After thinking for a couple minutes, I can only think about it behaving similarly to water, but maybe have a limit on the distance it affects, relative to the source block? Maybe lava shouldn't have this feature after all?
Also about the melting, maybe implementing it would be a bad idea, since there isn't even a temperature system in minecraft so lava is a never-ending source of heat. lmao

**Comment by 13rac1** [comment]
There's definitely room for Lava to have more functionality, but I'm not sure what would work well within the constraints of "Minecraft Science and Physics"

**Comment by nephatrine** [comment]
Since lava is much slower/more viscous, it probably should not erode through dirt quite like water does. Maybe looser materials like sand and gravel could still erode or melt though. Some blocks it could make sense to dry and eventually harden like maybe dirt -> coarse -> terracotta? I wish some of the BoP soils were part of vanilla so we'd have dried dirt and things like that as intermediates.

**Comment by 13rac1** [comment]
Filing this as "Maybe Someday", but closing for now.
