### ISSUE TITLE
Tag 1.16.5 on CurseForge to enable custom profiles to add the mod

### ISSUE THREAD

**Issue by paulhlschr** [13rac1/Minecraft-Water-Erosion#25]
**Question/Request**
Is it possible to tag WE on CurseForge with 1.16.5, as custom profiles and modpacks are not able to include the mod using the CurseForge client, if the profile runs on Forge 1.16.5?

**Comment by 13rac1** [comment]
Ahhh Thanks for the notice, been stuck working on other projects. I'll release a 1.16.5

**Comment by 13rac1** [comment]
Life got in the way back in 2021. I'm cleaning/refactoring to reduce the maintenance load. I've just release 8 versions for 1.19.1-1.19.4 for Forge and Fabric, I hope they work for you instead. LMK if you still need 1.16.5 though...
