### ISSUE TITLE
Small layer of water still erode land

### ISSUE THREAD

**Issue by DcNdrew** [13rac1/Minecraft-Water-Erosion#26]
Hi!
I'm using PhysEx for water and it has a thin layer of water which erodes the ground without flowing. I didn't find a way yet to make grass, dirt, sand and gravel permeable so the layers just lay around and erode the world.

**Comment by 13rac1** [comment]
Water Erosion was not built with [Phys](Exhttps://www.curseforge.com/minecraft/mc-mods/physex) in mind. I'm not surprised they don't work well together. This is a low priority bug. I'll leave the issue open, but I don't know if/when it'll be fixed.

**Comment by 13rac1** [comment]
Closing as "Won't Fix" I'll re-open if I ever work on it.
