### ISSUE TITLE
Plans for 1.19.3 Fabric Version?

### ISSUE THREAD

**Issue by Cape-City** [13rac1/Minecraft-Water-Erosion#29]
Hi,

the mod looks amazing and would be an extremly benefit for my curseforge fabric 1.19.3 modpack.

grettings
Monty

**Comment by 13rac1** [comment]
Due to the number of requests, I decided to just release 8 versions for 1.19.1-1.19.4 for Forge and Fabric. 😆 😵 It's here: [water-erosion-1.19.3-fabric-1.1.4.jar](https://www.curseforge.com/minecraft/mc-mods/water-erosion/files/4479602)

**Comment by Cape-City** [comment]
❤️ Wonderful! I will test it and happy eastern! thnx for all your work!
